name: V2ex

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
  schedule:
    - cron: 30 1 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/v2ex-action@master
        with:
          webhook: ${{ secrets.WEBHOOK }}
          secret: ${{ secrets.SECRET }}
          count: 8
